#include "Geometry/include/hasx.hpp"
#include "Base/include/nearestNeighbor.hpp"
#include "Base/include/rkky.hpp"
#include "Base/include/hasxStagMag.hpp"
#include "MonteCarlo/include/VectorModelManager.hpp"
#include "MonteCarlo/include/mcProfile.hpp"
#include "MonteCarlo/include/postProcessing.hpp"
#include <array>
#include <math.h>
#include <iostream>
#include <fstream>
#include <algorithm>